[phases.setup]
nixPkgs = ["python39", "python39Packages.pip"]

[phases.install]
cmds = [
  "pip install -r backend/requirements.txt"
]

[start]
cmd = "cd /app && PYTHONPATH=/app python -m uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
